### ISSUE TITLE
Strange behaviour when converting.

### ISSUE THREAD

**Issue by paolodep36** [sentinel-toolkit/sentinel-toolkit#12]
could i have an explanation on this kind of behavior? if i enter very high values  in the wavelenght range only the first two rows have non-zero values in all bands, in the other rows i have non-zero values only in band b12.

I used this settings: `s2_srf_options = S2SrfOptions(satellite='A', wavelength_range=(360, 2400))
illuminant = get_well_known_illuminant('identity', (360, 2400))
converter.convert_ecostress_to_sentinel_csv(s2_srf_options, illuminant)`

**Comment by gdgenchev** [comment]
Wooow, I had to debug this for some time. This is not related to the previous submit and seems to be a bug that was unknown until you found it 🥇It seems I have used a local variable while looping through the spectral distributions with the same name as an outer scope variable and this has lead to this weird issue. I will now change the local variable to have its own name, so that it does not interfere with the outer variable I will create a branch and will put the fix right now, so you can have it.

**Comment by gdgenchev** [comment]
I fixed this in this branch - https://github.com/sentinel-toolkit/sentinel-toolkit/tree/12-strange-behaviour-when-converting
Now the zero values in lower bands are correct and correspond to ecostress examples that have no data in the lower wavelength range and instead have data only in i.e. 2000+. Please check and confirm that now it works. 
If everything is alright, I will merge to master and release a new version of the library. Thank you!

**Comment by paolodep36** [comment]
tested and it seems to work. Tomorrow i will do some other testing to learn more about this library. i would like to know more about the rationale behind the conversion. My main use will be converting from ecostress to sentinel responses and find similar spectral values of a particular material  corrispondent to pixels in a scene.
